# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MarkovitzRRRCpp <- function(R, lambda, max_iter = 10000L, step_size_type = 's', step_size_constant = 1.e-3, tolerance = 1.e-15) {
    .Call(`_markovitzRRR_MarkovitzRRRCpp`, R, lambda, max_iter, step_size_type, step_size_constant, tolerance)
}

