# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MarkovitzRRRCpp <- function(R, lambda, objective_type = 'd', penalty_type = 'd', step_size_type = 'd', step_size_constant = 1.e-3, max_iter = 10000L, tolerance = -1.) {
    .Call(`_markovitzRRR_MarkovitzRRRCpp`, R, lambda, objective_type, penalty_type, step_size_type, step_size_constant, max_iter, tolerance)
}

